POST http://localhost:8080/api/v1/createUser
content-type: application/json

{
    "name" : "test",
    "email" :"p@gmail.com",
    "phone" :"123456789",
    "type" :  3

}

# {
#     "name" : "Bapi",
#     "phone" :"01834284316",
#     "type" :  6

# }